### ISSUE TITLE
Examples of Spring1D usage?

### ISSUE THREAD

**Issue by rkmore** [BriefFiniteElementNet/BFE.Net#3]
Hello.  I was wondering if you have any examples of Spring1D usage?  

I have used Springs in Abaqus and am pretty familiar with their use but I can't for the life of me get them to work as I would expect in BFE.NET

Do you have any examples you could share?

Thank you.

**Comment by epsi1on** [comment]
```Spring1D``` behaves like a truss element with stiffness of ``Spring1d.K`` [N/m]. Stiffness of ``TrussElement`` is equal to `E*A/L` but Spring1D have a direct stiffness value.
There is also a difference between behaviors of Truss and Spring, if ``Spring1D.StartNode`` and ``Spring1D .EndNode`` be on exactly one location (both have equalLocation), then it is like that two nodes are connected with three spring elements in X, Y and Z directions which makes Spring1D element to completely tie two nodes together in all three dimensions. but if Truss element's start and end nodes be on same location, then it probably makes an error because `E*A/L = Number / Zero`.
